import{a as S,S as v,i}from"./assets/vendor-BjmtRwYh.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function c(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();const P="45205333-a930dfeeeabac87545cb9c1b9",q="https://pixabay.com/api/",R=15;async function h(o,r=1){try{return(await S.get(q,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:R}})).data}catch{throw new Error("Failed to fetch images")}}const m=document.querySelector(".gallery"),g=document.querySelector(".load-more");function f(o){const r=o.map(({webformatURL:c,largeImageURL:e,tags:t,likes:n,views:w,comments:L,downloads:E})=>`
      <div class="photo-card">
        <a href="${e}" class="gallery-link">
          <img src="${c}" alt="${t}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${n}</p>
          <p class="info-item"><b>Views</b> ${w}</p>
          <p class="info-item"><b>Comments</b> ${L}</p>
          <p class="info-item"><b>Downloads</b> ${E}</p>
        </div>
      </div>
    `).join("");m.insertAdjacentHTML("beforeend",r),new v(".gallery a").refresh()}function k(){m.innerHTML=""}function C(){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",position:"topRight",backgroundColor:"#EF4040"})}function p(){document.querySelector(".loader").classList.remove("hidden")}function d(){document.querySelector(".loader").classList.add("hidden")}function F(){g.classList.remove("hidden")}function y(){g.classList.add("hidden")}function M(){i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",theme:"dark",position:"topRight",backgroundColor:"#2196F3"})}function $(){const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}const b=15;let l="",s=1,u=0;document.querySelector("#search-form").addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements.searchQuery.value.trim(),l===""){i.warning({title:"Warning",message:"Please enter a search query!",theme:"dark",position:"topRight",backgroundColor:"#FFA000"});return}s=1,k(),y(),p();try{const r=await h(l,s);d(),u=r.totalHits,r.hits.length===0?C():(f(r.hits),u>b&&F())}catch{d(),i.error({title:"Error",message:"Something went wrong. Please try again later.",theme:"dark",position:"topRight",backgroundColor:"#EF4040"})}});document.querySelector(".load-more").addEventListener("click",async()=>{s+=1,p();try{const o=await h(l,s);d(),f(o.hits),$(),s*b>=u&&(y(),M())}catch{d(),i.error({title:"Error",message:"Something went wrong. Please try again later.",theme:"dark",position:"topRight",backgroundColor:"#EF4040"})}});
//# sourceMappingURL=commonHelpers.js.map
